version: "3.9"

services:
  server:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    hostname: server
    environment:
      CLICKHOUSE_DB: Expenses
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    volumes:
      - ./db:/var/lib/clickhouse
      
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource, vertamedia-clickhouse-datasource
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
